- docs/_config.yml
- docs/_sass/minima/_base.scss
- Edit title of website and link to GitHub repository
- Close #4
> Update Jekyll site-wide settings

- docs/AboutUs.md
- docs/team/jasonqiu212.md
- Add headers for my PPP
- Add link from `AboutUs` page to my PPP
- Address #5
> Add skeletal Project Portfolio Page

- docs/UserGuide.md
- Change AB3 commands to comply with the new convention
- Add documentation for `add_task` command
- Address #7
> Update `UserGuide` Page

- docs/AboutUs.md
- docs/team/santosh3007.md
- Addresses #2 
- Addresses #5
> Update `AboutUs` page and Project Portfolio Page

- docs/DeveloperGuide.md
- Update and add non-functional requirements in developer guide
- Address #6
> Add NFRs for `DeveloperGuide` Page

- docs/UserGuide.md
> Remove AB3 traces from user guide

- src/main/java/swift/logic/commands/ListCommand.java
- src/main/java/swift/logic/commands/ListContactCommand.java
- src/main/java/swift/logic/parser/AddressBookParser.java
- src/test/java/swift/logic/LogicManagerTest.java
- src/test/java/swift/logic/commands/ListCommandTest.java
- src/test/java/swift/logic/parser/AddressBookParserTest.java
> Rename `list` command to `list_contact` command

- docs/index.md
> Docs: update index page

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
> Enhance Base UI

- src/main/java/swift/logic/commands/EditContactCommand.java
> ✨ Fix: change edit command to edit_contact command

- src/main/resources/view/DarkTheme.css
> Fix: update Contacts Tab UI

- build.gradle
- src/main/java/swift/MainApp.java
- src/main/java/swift/logic/commands/DeleteContactCommand.java
- src/main/java/swift/logic/parser/AddContactCommandParser.java
- src/main/java/swift/logic/parser/AddressBookParser.java
- src/main/java/swift/logic/parser/DeleteContactCommandParser.java
- src/test/java/swift/logic/LogicManagerTest.java
- src/test/java/swift/logic/commands/DeleteContactCommandTest.java
- src/test/java/swift/logic/parser/AddContactCommandParserTest.java
- src/test/java/swift/logic/parser/AddressBookParserTest.java
- src/test/java/swift/logic/parser/DeleteContactCommandParserTest.java
> Rename `delete` command to `delete_contact`

- README.md
- docs/AboutUs.md
- docs/DevOps.md
- docs/DeveloperGuide.md
- docs/Documentation.md
- docs/Logging.md
- docs/SettingUp.md
- docs/Testing.md
- docs/UserGuide.md
- docs/_sass/minima/_base.scss
- docs/_sass/minima/custom-styles.scss
- docs/_sass/minima/custom-variables.scss
- docs/index.md
- Add implementation of `find_task` command
- Add smooth scrolling for website
- Change heading color
- Address #75
> Add implementation of `find_task` command in DG

- docs/DeveloperGuide.md
- Add Implementation of Autocomplete and Command Suggestion
- Addresses #75
> Add Implementation of AutoComplete and Command Suggestion in DG

- docs/DeveloperGuide.md
> Add implementation of tasks main panel to DG

- src/main/java/swift/model/AddressBook.java
- src/main/java/swift/model/bridge/PersonTaskBridgeList.java
- src/test/java/swift/model/bridge/PersonTaskBridgeListTest.java
> Fix: fix bridges not loaded during startup

- src/main/java/swift/logic/commands/AddTaskCommand.java
- src/test/java/swift/logic/commands/AddTaskCommandTest.java
> Fix: use relative person index when adding task

- docs/_includes/custom-head.html
- src/main/java/swift/logic/parser/AddTaskCommandParser.java
- src/main/java/swift/logic/parser/EditTaskCommandParser.java
- src/main/resources/view/TaskListCard.fxml
> Fix: fix name of deadline fxml component

- docs/UserGuide.md
> Doc: add select commands into UG

- docs/UserGuide.md
- src/main/java/swift/logic/commands/AssignCommand.java
- src/main/java/swift/logic/commands/CommandSuggestor.java
- src/main/java/swift/logic/commands/CommandType.java
- src/main/java/swift/logic/commands/ListContactCommand.java
- src/main/java/swift/logic/commands/ListTaskCommand.java
- src/main/java/swift/logic/parser/AddressBookParser.java
- src/main/java/swift/logic/parser/AssignCommandParser.java
- src/main/java/swift/logic/parser/CliSyntax.java
- src/main/java/swift/ui/MainWindow.java
- src/test/java/swift/logic/commands/AssignCommandTest.java
- src/test/java/swift/logic/commands/ListTaskCommandTest.java
- src/test/java/swift/logic/parser/AssignCommandParserTest.java
- `list_contact` and `list_task` no longer hide the other list
Resolves #97
Resolves #109
> Feat: add assign command

- src/main/java/swift/MainApp.java
- src/main/java/swift/logic/commands/CommandType.java
- src/main/java/swift/logic/commands/SelectContactCommand.java
- src/main/java/swift/logic/commands/SelectTaskCommand.java
- src/main/java/swift/ui/MainWindow.java
- src/main/java/swift/ui/PersonTaskCard.java
- src/main/java/swift/ui/PersonTaskListPanel.java
- src/main/java/swift/ui/TaskCard.java
- src/main/java/swift/ui/TaskPersonListPanel.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonTaskCard.fxml
- src/main/resources/view/TaskPersonCard.fxml
- src/test/java/swift/logic/commands/SelectContactCommandTest.java
- src/test/java/swift/logic/commands/SelectTaskCommandTest.java
> Feat: show all tasks and contacts on `list`

- src/main/java/swift/logic/commands/AddTaskCommand.java
- src/main/java/swift/logic/commands/EditTaskCommand.java
> Fix `edit_task` and `add_task` command usage

- src/main/java/swift/logic/commands/AddTaskCommand.java
- src/main/java/swift/model/util/SampleDataUtil.java
- src/main/java/swift/storage/JsonAdaptedTask.java
> Feat: add `isDone` for task to storage

- docs/UserGuide.md
- src/main/java/swift/logic/commands/AssignCommand.java
- src/main/java/swift/logic/commands/UnassignCommand.java
- src/main/java/swift/ui/MainWindow.java
> 📝 Docs: add user guide for clear command

- src/main/java/swift/model/ModelManager.java
- src/main/java/swift/model/task/Deadline.java
- src/main/java/swift/model/task/Task.java
- src/main/java/swift/model/task/TaskName.java
- src/test/java/swift/logic/commands/EditTaskCommandTest.java
- src/test/java/swift/logic/commands/FindTaskCommandTest.java
> Feat: sort tasks by chronological order

- src/main/java/swift/ui/MainWindow.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- Change menu bar from dropdown menu to buttons
- Toggle tabs with shortcut keys (CTRL + TAB)
> Menu bar Enhancements

- src/main/java/swift/ui/MainWindow.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
Underlines the menu button of the tab that the app is currently showing
> Style: underline menu button

- src/main/java/swift/commons/core/GuiSettings.java
> Perf: fix default window size

- src/main/java/swift/ui/MainWindow.java
Some tasks do not display tags properly after a few command runs
> Bug: Fix task tags display

- docs/UserGuide.md
> Docs: update command descriptions involving displayed index

- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/PersonListPanel.fxml
- src/main/resources/view/PersonTaskCard.fxml
- src/main/resources/view/PersonTaskListPanel.fxml
- src/main/resources/view/ResultDisplay.fxml
- src/main/resources/view/TaskListCard.fxml
- src/main/resources/view/TaskListPanel.fxml
- src/main/resources/view/TaskPersonCard.fxml
- src/main/resources/view/TaskPersonListPanel.fxml
> Bug: fix javafx version

- docs/team/peppapighs.md
> Docs: update PPP draft

- docs/UserGuide.md
> Docs: update deadline specification in ug

- docs/UserGuide.md
> Docs: fix find_task user guide tense inconsistency

- README.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/index.md
- docs/team/jasonqiu212.md
> Add Jason's PPP draft

- docs/team/shenyicui.md
> :memo: Docs: add ppp draft

- docs/team/yunruu.md
> Docs: update PPP

- src/main/java/swift/logic/commands/AddTaskCommand.java
- src/test/java/swift/logic/commands/AddTaskCommandTest.java
> Fix: display error message when add_task contact index is invalid

- src/main/java/swift/commons/core/Messages.java
- src/main/java/swift/logic/commands/AddContactCommand.java
- src/main/java/swift/logic/commands/DeleteContactCommand.java
- src/main/java/swift/logic/commands/EditContactCommand.java
- src/main/java/swift/logic/commands/FindContactCommand.java
- src/main/java/swift/logic/commands/ListContactCommand.java
- src/main/java/swift/logic/commands/SelectContactCommand.java
> Fix: change terminology from person to contact

- src/main/java/swift/logic/commands/MarkTaskCommand.java
- src/main/java/swift/logic/commands/UnmarkTaskCommand.java
> Fix: mark/unmark command no longer execute select contact/task

- docs/UserGuide.md
- src/main/java/swift/model/person/PersonName.java
- src/main/java/swift/model/task/TaskName.java
> Feat: allow special characters in contact and task name

- src/main/java/swift/model/person/Person.java
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/java/swift/model/AddressBookTest.java
- src/test/java/swift/model/person/PersonTest.java
- src/test/java/swift/model/person/UniquePersonListTest.java
Two contacts will be the same only if they have the same:
- Name
- Phone number
- Email address
- Home address
- Resolve #152
> Edit `isSamePerson` check restriction

- src/main/java/swift/ui/PersonTaskListPanel.java
- src/main/java/swift/ui/TaskPersonListPanel.java
- src/main/resources/view/PersonListPanel.fxml
- src/main/resources/view/PersonTaskListPanel.fxml
- src/main/resources/view/TaskListPanel.fxml
- src/main/resources/view/TaskPersonListPanel.fxml
> Fix: fix UI panel headers

- src/main/resources/view/DarkTheme.css
> Fix: make context menu fields visible

- src/main/java/swift/logic/commands/CommandSuggestor.java
- src/main/java/swift/ui/CommandBox.java
- src/main/resources/view/DarkTheme.css
- src/test/java/swift/logic/commands/MarkTaskCommandTest.java
- src/test/java/swift/logic/commands/UnmarkTaskCommandTest.java
- src/test/java/swift/testutil/EditTaskDescriptorBuilder.java
- src/test/java/swift/testutil/TaskBuilder.java
- Resolves #159 
- Resolves #155 
- Resolves #170 
- Resolves #129
> Autocomplete Fixes

- docs/UserGuide.md
> Fix: fix table of contents in user guide

- src/main/java/swift/logic/commands/AddTaskCommand.java
- src/main/java/swift/logic/commands/DeleteTaskCommand.java
- src/main/java/swift/logic/commands/EditTaskCommand.java
- src/main/java/swift/model/Model.java
- src/main/java/swift/model/ModelManager.java
- src/test/java/swift/logic/commands/AddContactCommandTest.java
- src/test/java/swift/logic/commands/AddTaskCommandTest.java
> Fix: remove hot update method from command execution

- src/main/resources/view/MainWindow.fxml
- Resolves #224 
- Resolves #150
> Fix: command output box header

- src/main/java/swift/logic/parser/AddTaskCommandParser.java
> Fix: display proper error message for add_task

- src/main/java/swift/logic/commands/EditTaskCommand.java
> Fix: edit_task no longer forces unmark a task

- src/test/java/swift/storage/JsonAdaptedBridgeTest.java
- src/test/java/swift/storage/JsonAdaptedTaskTest.java
- src/test/java/swift/storage/StorageManagerTest.java
- src/test/java/swift/testutil/TypicalTasks.java
- Increase code coverage by 1.40%
- Resolve #223
> Tests: add tests for storage

- src/main/java/swift/logic/commands/AddTaskCommand.java
- src/main/java/swift/model/task/Deadline.java
- Fixes the DateTime issue for silent failure of wrong dates
- Fixes message specificity for error message on dates
- Resolves #180 
- Resolves #177
> :bug: fix DateTime error

- src/main/resources/view/PersonListCard.fxml
> Fix: early truncation of description in contact card

- src/main/java/swift/model/task/Deadline.java
- src/test/java/swift/model/bridge/PersonTaskBridgeTest.java
- src/test/java/swift/model/tag/TagTest.java
- src/test/java/swift/model/task/DeadlineTest.java
- src/test/java/swift/model/task/DescriptionTest.java
- src/test/java/swift/model/task/TaskNameTest.java
> Test: add tests for Model

- docs/UserGuide.md
> Docs: add autocomplete FAQ

- src/main/java/swift/ui/CommandBox.java
- Resolves #238 
- Fix backspace bug which prevents users from editing entered commands
> Fix backspace bug

- docs/UserGuide.md
> Add caution note for `clear` command

- docs/team/santosh3007.md
> Update Santosh PPP

- docs/UserGuide.md
> :memo: Docs: UG add `find_contact` caption
